### ISSUE TITLE
Feature request: mountable MxLEDBitPCB

### ISSUE THREAD

**Issue by fi0** [swanmatch/MxLEDBitPCB#12]
Just an idea ..
2 tiny mounting holes will be useful for hand wired dactyl-like keyboards so that we don't need to use hot glue.

This is something similar on the NeoKey Socket Breakout.

**Comment by swanmatch** [comment]
@fi0 

Sorry for the late reply!

Is this the hole you're referring to?
I've already drilled those holes on all the boards!

![image](https://user-images.githubusercontent.com/6962187/115110091-8341f680-9fb4-11eb-8d39-1a864b1db294.png)
