### ISSUE TITLE
SK6812 solder side ?

### ISSUE THREAD

**Issue by coliss86** [swanmatch/MxLEDBitPCB#14]
Hi,

could you tell me if the led is in the correct position according to the following photos ?
![image](https://user-images.githubusercontent.com/23615562/117705326-34ab0500-b1cc-11eb-90b2-55d9c0cae476.png)

If so, the led is facing the bottom. I don't understand why it isn't oriented to the top of the keyboard in order to glow through the switch ?

Regards

**Comment by coliss86** [comment]
ok, I found my error : I'm using SK6812 MINI**-E** instead of SK6812 MINI :(

**Comment by swanmatch** [comment]
@coliss86 
Please refer to the following.
Photo PCB looks Altana.

project | switch | Kailh socket availability | led | Through-hole diode | SOD-123
--- | --- | --- | --- | --- | ---
Nexus | MX | No | SK6812MINI | Yes | No
Altana | MX | Yes | SK6812MINI | Yes | No
Suxen | MX | No | YS-SK6812MINI | Yes | Yes (*)
Container | MX | Yes | YS-SK6812MINI | Yes | Yes (*)
Choc | KailhLowProfile | No | YS-SK6812MINI | No | Yes

**Comment by fi0** [comment]
@swanmatch is YS-SK6812MINI the same as SK6812MINI-E?

**Comment by swanmatch** [comment]
@fi0 Yes!

**Comment by safijari** [comment]
So I should have gotten Container instead of Altana ... Dang it

**Comment by safijari** [comment]
https://www.reddit.com/r/olkb/comments/sytzj2/when_you_order_the_wrong_leds_but_are_too_stubborn/

Ok, for anyone that stumbles here in the future. here's my brief rant on how you still could use these LEDs if you ordered the wrong PCB.
