### ISSUE TITLE
where to find the pcb used to mount the mcu

### ISSUE THREAD

**Issue by pathnirvana** [swanmatch/MxLEDBitPCB#15]
this is question rather than a issue.
anyone know where to find the pcb used to mount the mcu in the wiring diagram in the readme?

**Comment by l4u** [comment]
https://github.com/swanmatch/MxLEDBitPCB/tree/master/MxLEDBitPCB-promicro

**Comment by pathnirvana** [comment]
Many thanks @l4u 
by the way when I was printing the container.zip via jclpcb few days ago they were rejecting the order mentioning that breakout tabs were too small (had to be at least 4mm to prevent the panels from coming apart during production). However after I mentioned that my previous order of altana was printed without any issues they agreed to proceed with the order. Just FYI

**Comment by swanmatch** [comment]
@l4u Thanks for the follow!
@pathnirvana I hope everything goes well for you.
