### ISSUE TITLE
Container spacing issue

### ISSUE THREAD

**Issue by christrotter** [swanmatch/MxLEDBitPCB#16]
I submitted the container.zip (the one from this repo - I did not make it) to JLCPCB and got this audit failure:
```
Dear the spacing from slot to slot and slot to board edge are too small which will cause the board broken easily,please kindly increase it to 4mm at least.Thanks.
```
![image](https://user-images.githubusercontent.com/8292406/152674818-ad598c2b-2448-4a56-8803-95ce64c010c9.png)

I'm guessing they mean the connectors?
![image](https://user-images.githubusercontent.com/8292406/152675023-6e28ef1d-087c-4659-93a5-41bd7ac5c5f2.png)

I have asked for clarity in the mean time...if I can figure out what software to use, I'll try and submit a PR to fix once they tell me the specific problem.

**Comment by christrotter** [comment]
My exact message, accompanied by that picture with the red arrrow...
```
For clarity - this panel is intended to be broken apart into 25 pieces for use.  Is your concern rather for the manufacturing process having breakages?
In the attached - is the red arrow pointing at what you want increased to at least 4mm?
```

And their response...
```
Dear Sir,
Yes,please add the indicated spacing to 4 mm at least.
```

So I'm gonna go with they want those little board-to-board connection points to be 4mm.  I will do some research on what software to use to edit the files...

**Comment by christrotter** [comment]
So Kicad seems to be what is used, and I have no idea what I'm doing here.  I might have to go the amoeba royale v2.0 route instead. :(

**Comment by khominhvi** [comment]
I had the same issue with JLCPCB.

In another post, which seems to have disappeared, recommended another manufacturer; elecrow, which is what I used to have the pcbs manufactured.

**Comment by christrotter** [comment]
Interesting - I checked them out @khominhvi , do you recall what order settings you used?  Elecrow seems to have less options.   Like no panel settings...

![image](https://user-images.githubusercontent.com/8292406/152842005-0b84d298-eaaa-4631-8705-f44896b654e4.png)

**Comment by khominhvi** [comment]
![image](https://user-images.githubusercontent.com/5494481/152842482-ad239402-c79e-45bf-8f51-977996ba16b8.png)

**Comment by christrotter** [comment]
You are a champ, awesome, gonna give it a shot.

**Comment by khominhvi** [comment]
Np, good luck. 

I also managed to find the thread I was referring to earlier, for anyone who is interested: https://github.com/swanmatch/MxLEDBitPCB/pull/13

**Comment by christrotter** [comment]
I ended up ordering Amoeba Royale's from JCLPCB and the Container's from Elecrow.  Will post back results to this issue.

It might be worthwhile updating the readme with a section on ordering, I'd be happy to contribute to that.

**Comment by swanmatch** [comment]
@christrotter @khominhvi Thank you for your interest.(and sorry for late reply...)
I am aware of the design rules of JLCPCB that will be played by it.
I just can't easily fold it by hand when I unfold the solid.
I order from Elecrow all the time and have manufactured thousands of them and have never been rejected.
Thanks

**Comment by swanmatch** [comment]
FYI @christrotter 
https://github.com/swanmatch/MxLEDBitPCB/issues/15#issuecomment-863041554

**Comment by christrotter** [comment]
@swanmatch Thanks!  If you'd like I could submit a PR with some 'ordering help' in the english readme, might help others in future.

**Comment by swanmatch** [comment]
@christrotter That's a great suggestion for me!

**Comment by christrotter** [comment]
Made a PR for you! https://github.com/swanmatch/MxLEDBitPCB/pull/17
