### ISSUE TITLE
difference between altana, choc, container, nexus, suxen

### ISSUE THREAD

**Issue by smallstepman** [swanmatch/MxLEDBitPCB#5]
Hi!

I'm a bit puzzled about choosing the right version for my project. 
In your repository, I could find the following switch PCB KiCAD projects:
- altana
- choc
- container
- nexus
- suxen

After reading `readme_en.md` I assume altana can be used with kailh switches, whereas nexus cannot?

I did try to compare these two in KiCAD and I can spot many differences but I don't understand why there are differences.
![image](https://user-images.githubusercontent.com/21069150/101300892-6e4f9c80-3837-11eb-9a6e-7dc9369f202f.png)
(nexus on the left, altana on the right)

Could you please explain what are the differences between these 5 versions?

Which version should I pick for Cherry MX switches? And which one for Kailh switches?

Cheers!

**Comment by swanmatch** [comment]
I'm sorry I didn't update the document in time.
Each project differs in its corresponding LED and whether or not Kailh's switch socket can be used.

Project | Switch | Socket | LED
-|-|-|-
Nexus | MX | No | SK6812MINI
Altana | MX | Yes | SK6812MINI
Suxen | MX | No | YS-SK6812MINI
Container | MX | Yes | YS-SK6812MINI
Choc | KailhLowProfile | No | YS-SK6812MINI

* [YS-SK6812MINI](https://yushakobo.jp/shop/ys-sk6812mini-e/)
* [SK6812MINI](https://yushakobo.jp/shop/sk6812mini-10/)
* [Kailh Socket](https://kbdfans.com/products/mechanical-keyboard-switches-kailh-pcb-socket)

kailh's MX compatible switches (such as Kailh Pro Burgundy) can be used outside of Choc.
KailhLowProfile can only be used with Choc.

**Comment by smallstepman** [comment]
Beautiful, I wasn't sure what Kailh socket was, thank you for the link. 
Everything is clear, many thanks for the swift reply and your great work!

**Comment by smallstepman** [comment]
Sorry, two questions actually :))

1. What makes Nexus not compatible with the Kailh socket, and what makes Altana compatible with the socket?
From KiCAD scheme I understand Nexus has holes for the switch legs:
![image](https://user-images.githubusercontent.com/21069150/101359599-cbca0480-389c-11eb-95d9-f7f79223281a.png)
whereas Altana does not:
![image](https://user-images.githubusercontent.com/21069150/101359636-d97f8a00-389c-11eb-93a9-fd0f83277ce4.png)
But why does this make a difference in socket compatibility? Or maybe it's something else?
In my mind, the pins coming out from the switch, are supposed to go through the PCB no matter what:  
![image](https://user-images.githubusercontent.com/21069150/101359818-1481bd80-389d-11eb-936f-408c950e3d1c.png)
But maybe on that picture ([source](https://imgur.com/a/3xqx0M3)), the Kailh socket is mounted on another side than originally planned in your project?
Correct me if I'm wrong, but it seems to me that having no holes for the switch legs, would require precise measurement of the distance between the top-plate, and the PCB (which I perceive as unwanted)?
I hope I didn't mix something up...


2. Can you please outline the differences in performance between YS-SK6812MINI and SK6812MINI, if any?

**Comment by swanmatch** [comment]
1. When you use the Kailh socket, which needs a specific design, you cannot  share. 
  Nexus has plated holes, and Altana? has mechanical holes.
  It's even easier to understand if you watch 3D viewer.
2. Ys-sk6812mini has tabs, so it's easy to solder it.
